name: Tag

on:
  create:
    tags:
      - "*"

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Run bash script
        run: bash script.sh
      - name: Modify CHANGELOG.md file
        run: |
          sed -i 's/old-text/new-text/g' CHANGELOG.md
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Update CHANGELOG.md
          commit-message: Update CHANGELOG.md
          body: |
            This PR updates the CHANGELOG.md file.
          branch: update-CHANGELOG
          token: ${{ secrets.GITHUB_TOKEN }}
